### ISSUE TITLE
Can't get xdebug working with platformsh recipe and PHPStorm

### ISSUE THREAD

**Issue by aimfeld** [lando/platformsh#111]
I have tried quite a bit and read various sources, but I just can't figure out how to get xdebug working with lando and the platform.sh recipe. Otherwise, my local site runs fine. Any help is greatly appreciated. My OS is Windows 10.

Here are my settings:

.lando.yml
```
name: surveylab-blueprint
recipe: platformsh
config:
  id: bftge3smv4qgi
  xdebug: true
env_file:
  - .env
excludes:
  - .idea
  - .platform
  - .yarn
  - node_modules
  - vendor
  - "!vendor/cloud-solutions"
```

.platform.app.yaml
```
runtime:
  extensions:
    - redis
    - xdebug
  xdebug:
    idekey: PHPSTORM  # See https://docs.platform.sh/languages/php/xdebug.html

...
```

php.ini in /app 
```
; Xdebug
xdebug.remote_connect_back = 1
xdebug.idekey = "PHPSTORM"

...
```

PHP Settings:
![image](https://user-images.githubusercontent.com/760330/101347414-58b79280-388a-11eb-90cf-dacd53c22897.png)

CLI Interpreter:
![image](https://user-images.githubusercontent.com/760330/101347481-74bb3400-388a-11eb-8a19-df04c7bb8a13.png)

Debug Settings:
![image](https://user-images.githubusercontent.com/760330/101347583-94eaf300-388a-11eb-875e-6000ebf82c0b.png)

DBGp Proxy: 
![image](https://user-images.githubusercontent.com/760330/101347637-acc27700-388a-11eb-8002-9ab3c19eb896.png)

PHP Info:
![image](https://user-images.githubusercontent.com/760330/101347811-e8f5d780-388a-11eb-8201-9df38a9322f3.png)
![image](https://user-images.githubusercontent.com/760330/101348001-370adb00-388b-11eb-8440-b09b74a1445d.png)
![image](https://user-images.githubusercontent.com/760330/101348040-4c800500-388b-11eb-9428-8f04e8c5cd30.png)
![image](https://user-images.githubusercontent.com/760330/101348083-60c40200-388b-11eb-8de6-7f9e6c794857.png)
