### ISSUE TITLE
PLATFORM_RELATIONSHIPS not set when using xdebug and php 8.0

### ISSUE THREAD

**Issue by simonkey** [lando/platformsh#139]
The environment variable PLATFORM_RELATIONSHIPS is not set when using xdebug in php 8.0, maybe for php 8.1 too. This is quite a problem when using something like https://github.com/platformsh/symfonyflex-bridge to get e.g. the DATABASE_URL.

Config:

```
runtime:
    xdebug:
        idekey: PHPSTORM
    extensions:
        - xdebug # optional
```
If the extension is enabled or not seems not to be the problem.
Internally the platform.sh-image uses a different PHP-FPM-process (https://docs.platform.sh/languages/php/xdebug.html#setting-up-xdebug) when xdebug is used.
