### ISSUE TITLE
Use stable tag instead of latest tag for docker images

### ISSUE THREAD

**Issue by simonkey** [lando/platformsh#163]
Platform.sh uses the tag "stable" for the latest stable build of their docker images since a few months. Therefore no new images are pulled and used if there are any updates in the images. 

Is there a way to change this behavior and/or set the tag to be used? 

Especially there should be imagick available for PHP 8.0, but the image tagged with latest misses this php extension. The stable image can be pulled with `docker pull docker.registry.platform.sh/php-8.0:stable`, but it isn't used when rebuilding lando with `lando rebuild -y`.

**Comment by simonkey** [comment]
**Update:** The stable image can be used by an override in the `.lando.yml` as described in https://docs.lando.dev/guides/overriding-a-service-version.html.

In the case of php 8.0 will look like that:

```
services:
    app:
        overrides:
            image: docker.registry.platform.sh/php-8.0:stable
```
