### ISSUE TITLE
Locking down ports for external database connection not working

### ISSUE THREAD

**Issue by jasloe** [lando/platformsh#171]
I’m having trouble locking down ports using the platformsh recipe with multiple database containers.

I'm on the latest versions of Lando and the platformsh CLI. Here are the relevant excerpt from my configuration:
```
[services.yaml]
db:
  type: mariadb:10.4
  disk: 2048

db2:
  type: mariadb:10.4
  disk: 2048

[.platform.app.yaml]
relationships:
  database: "db:mysql"
  database2: "db2:mysql"

[.lando.yml]
recipe: platformsh
services:
  db:
    portforward: 3307
  db2:
    portforward: 3308
```
`lando rebuild -y` returns:
```
  { service: 'db',
    type: 'platformsh-mariadb',
    creds:
     [ { internal_hostname: 'database.internal', path: 'main', port: 3306, user: 'user' } ],
    internal_connection: { host: 'db', port: '3306' },
    external_connection: { host: '127.0.0.1', port: '63259' },

  { service: 'db2',
    type: 'platformsh-mariadb',
    creds:
     [ { internal_hostname: 'database2.internal', path: 'main', port: 3306, user: 'user' } ],
    internal_connection: { host: 'db2', port: '3306' },
    external_connection: { host: '127.0.0.1', port: '63259' },
```
There's a nearly identical and now-closed issue at #39. Either there's a regression somewhere or I don't know what I'm doing. Trying to understand the[ lando logs](https://docs.lando.dev/help/logs.html) commands to troubleshoot this but the docs are 404.

**Comment by aimfeld** [comment]
@jasloe A colleague of mine experiences the same problem with lando 3.6.5. A temporary downgrade to 3.6.4 might help.

**Comment by jasloe** [comment]
@aimfeld thanks for replying. I'm now running 3.6.4 with mixed results. It seems to work fixing only one of the ports, i.e.:
```
services:
  db:
    portforward: 3309
  db2:
    portforward: 3310
```

```
    internal_connection: { host: 'db', port: '3306' },
    external_connection: { host: '127.0.0.1', port: '50907' },
```
```
  internal_connection: { host: 'db2', port: '3306' },
  external_connection: { host: '127.0.0.1', port: '3310' },
``` 
It's unpredictable which service's port if fixed. Not sure where to go next with troubleshooting.
