### ISSUE TITLE
Xdebug extension binary missing on php 8.1

### ISSUE THREAD

**Issue by yaronuliel** [lando/platformsh#178]
When configuring a `platformsh` recipe for project with `php:8.1` runtime to have xdebug enabled -
The `xdebug.ini` file is being loaded, but the extension binary (`xdebug.so`) is missing

```
❯ lando php -v
PHP Warning:  Failed loading Zend extension 'xdebug.so' (tried: /usr/lib/php/20210902-zts/xdebug.so (/usr/lib/php/20210902-zts/xdebug.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902-zts/xdebug.so.so (/usr/lib/php/20210902-zts/xdebug.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Warning: Failed loading Zend extension 'xdebug.so' (tried: /usr/lib/php/20210902-zts/xdebug.so (/usr/lib/php/20210902-zts/xdebug.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902-zts/xdebug.so.so (/usr/lib/php/20210902-zts/xdebug.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.1.0 (cli) ( ZTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.0, Copyright (c), by Zend Technologies
```

I used configuration override in my `.lando.yml` file:
```yaml
name: 1111-some-project
recipe: platformsh
config:
  id: 111122223333444
  overrides:
    app:
      runtime:
        extensions:
          - xdebug
```

When I run the same thing with `php:7.4` application runtime - everything works as expected

**Comment by keviny86** [comment]
```yaml
services:
  app:
    overrides:
      image: docker.registry.platform.sh/php-8.1:stable
```

Add this to your lando file will fix this issue, would be great if this could be solved without overriding image.
