### ISSUE TITLE
Error on build at /snapshot/cli/lib/shell.js

### ISSUE THREAD

**Issue by gabrovex** [lando/platformsh#22]
Using lando v3.4.1 on Linux Mint 18.2 because on the last version (>=v3.4.2) im experiencing [this error](https://github.com/lando/lando/issues/3182). recipe: platformsh.

Error on `lando rebuild`:
```
Rising anew like a fire phoenix from the ashes! Rebuilding app...
No stopped containers
Pulling cacheredis ... done
Pulling surveylab  ... done
Pulling mysql      ... done
surveylab uses an image, skipping
cacheredis uses an image, skipping
mysql uses an image, skipping
Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... done
ERROR ==> You cannot assign url testlando.lndo.site/:80 to more than one service! 
Creating network "testlando_default" with the default driver
Creating volume "testlando_data_surveylab" with default driver
Creating volume "testlando_home_surveylab" with default driver
Creating volume "testlando_data_mysql" with default driver
Creating volume "testlando_home_mysql" with default driver
Creating volume "testlando_data_cacheredis" with default driver
Creating volume "testlando_home_cacheredis" with default driver
Creating testlando_surveylab_1 ... done
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.rebuild (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/rebuild.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
Creating testlando_mysql_1      ... done
Creating testlando_cacheredis_1 ... done
Opening platform.sh containers... this may take a bit...
Scanning to determine which services are ready... Please standby...

[2021-10-26 14:35:51.067701] Launching command 'set -e
cd
# Wait a few seconds until DB container is running, otherwise phinx migrate fails on lando
if [ "$PLATFORM_ENVIRONMENT" = "lando" ]; then echo "Sleeping to wait for DB container..."; sleep 15; fi
vendor/bin/phing run-migrations
vendor/bin/phing clear-data
vendor/bin/doctrine orm:generate-proxies
vendor/bin/phing clear-caches
vendor/bin/phing import-project
vendor/bin/phing reset-accounts
'.

Sleeping to wait for DB container...
/bin/dash: 5: vendor/bin/phing: not found
```

This is our stripped down lando.yaml:
```
name: testlando
recipe: platformsh

services:
  surveylab:
    # Configure xdebug, see https://docs.lando.dev/config/php.html#configuration
    xdebug: "debug,develop"
    run:
      # Print deploy log, see https://github.com/cloud-solutions/blueprint/issues/583
      - cat /var/log/deploy.log

config:
  id: bftge3smv4qgi
  variables:
    surveylab:
      php:
        # Needed for debugging laminas-cli commands (not working).
        # xdebug.start_with_request: yes
  overrides:
    surveylab:
      runtime:
        extensions:
          - igbinary  # Required by redis, see https://github.com/lando/lando/issues/2788
          - redis
          - xdebug
          # Make xdebug work. Resources:
          # - https://docs.lando.dev/guides/lando-phpstorm.html
          # - https://untoldhq.com/blog/2019/08/02/when-lando-phpstorm-and-xdebug-setup-gets-hairy

env_file:
  - .env
 ```
