### ISSUE TITLE
Cannot set property 'route' of undefined

### ISSUE THREAD

**Issue by aimfeld** [lando/platformsh#24]
I'm trying to set up a new python-based project with the `platformsh recipe`, but when I run `lando start` or `lando rebuild`, I get the following error (and no other output). I'm using the newest Lando version `v3.4.2`.

```
ERROR ==> Cannot set property 'route' of undefined message=Cannot set property 'route' of undefined, stack=TypeError: Cannot set property 'route' of undefined
    at AsyncEvents.<anonymous> (/snapshot/cli/integrations/lando-platformsh/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.init (/snapshot/cli/lib/app.js)
    at initAndReport (/snapshot/cli/lib/app.js)
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
``` 

The project deploys without problems on platform.sh

Here's my `.lando.yml`
```
name: nft-tools
recipe: platformsh
config:
  webroot: .
  id: be24tiaetid5y
```

My `.platform/routes.yaml`
```
"https://{default}/":
    type: upstream
    upstream: "app:http"
"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
```

My .platform.app.yaml
```
name: app
type: "python:3.9"
relationships:
    postgresdatabase: 'dbpostgres:postgresql'

hooks:
    build: |
      ...
    deploy: |
      ...
crons:
  ...
disk: 1024
web:
    commands:
        start: bash ./scripts/start_command.sh
    upstream:
        socket_family: tcp
        protocol: http
    locations:
        "/":
            passthru: true
```
