### ISSUE TITLE
Platform recipe: [InvalidArgumentException] Specified project not found: <faulty-id>

### ISSUE THREAD

**Issue by bradley-baylis** [lando/platformsh#32]
1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already. ✔️
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate. ✔️

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

I was using v3.0.26 and have updated to v3.1.4 with a Ubuntu distro on WSL2.

**Tell us about your `.lando.yml`**

*lando.upstream.yml:*

```yml

name: platformsh-drupal9
recipe: platformsh
config:
  overrides:
    app:
      variables:
        d8config:
          "system.file:path:temporary": "/tmp"
        d8settings:
          "skip_permissions_hardening": 1
  tooling:
    drush:
      service: app

```

*lando.yml:*

```yml

name: avenue-road
services:
  node:
    type: 'node:12'
    globals:
      gulp-cli: latest
tooling:
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node
```
*.platform.app.yaml:*

```yml
name: 'app'
type: 'php:7.4'
dependencies:
    php:
        composer/composer: '^2'
runtime:
  extensions:
        - redis
relationships:
    database: 'db:mysql'
    redis: 'cache:redis'
disk: 2048
mounts:
    '/web/sites/default/files':
        source: local
        source_path: 'files'
    '/tmp':
        source: local
        source_path: 'tmp'
    '/private':
        source: local
        source_path: 'private'
    '/.drush':
        source: local
        source_path: 'drush'
    '/drush-backups':
        source: local
        source_path: 'drush-backups'
    '/.console':
        source: local
        source_path: 'console'
build:
    flavor: composer
hooks:
    build: |
        set -e
    deploy: |
        set -e
        php ./drush/platformsh_generate_drush_yml.php
        cd web
        drush -y cache-rebuild
        drush -y updatedb
        drush -y config-import
web:
    locations:
        '/':
            root: 'web'
            expires: 5m
            passthru: '/index.php'
            allow: false
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true
                '^/sites/sites\.php$':
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false
        '/sites/default/files':
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/sites/default/files'
            scripts: false
            rules:
                '^/sites/default/files/(css|js)':
                    expires: 2w
crons:
    drupal:
        spec: '*/19 * * * *'
        cmd: 'cd web ; drush core-cron'
```

This is the Drupal 9 template on Platform.sh docs.

**Tell us about the command you were running**

Either one of the following:
```bash
lando platform env
lando push
```

**Tell us about the error you got**

*lando platform env:*

```bash
lando 12:02:27 DEBUG ==> No update available. 
lando 12:02:27 VERBOSE ==> starting bootstrap at level engine... 
lando 12:02:27 VERBOSE ==> config bootstrap beginning... 
lando 12:02:27 DEBUG ==> emitting event pre-bootstrap-config 
lando 12:02:27 DEBUG ==> plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/index.js 
lando 12:02:27 DEBUG ==> plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/index.js 
lando 12:02:27 DEBUG ==> plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/index.js 
lando 12:02:27 DEBUG ==> plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/index.js 
lando 12:02:27 DEBUG ==> plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/index.js 
lando 12:02:27 DEBUG ==> plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/index.js 
lando 12:02:27 DEBUG ==> plugin lando-sharing loaded from /snapshot/lando/build/cli/plugins/lando-sharing/index.js 
lando 12:02:27 DEBUG ==> plugin lando-test loaded from /snapshot/lando/build/cli/plugins/lando-test/index.js 
lando 12:02:27 DEBUG ==> plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/index.js 
lando 12:02:27 DEBUG ==> plugin lando-acquia loaded from /snapshot/lando/build/cli/integrations/lando-acquia/index.js 
lando 12:02:27 DEBUG ==> plugin lando-lagoon loaded from /snapshot/lando/build/cli/integrations/lando-lagoon/index.js 
lando 12:02:27 DEBUG ==> plugin lando-pantheon loaded from /snapshot/lando/build/cli/integrations/lando-pantheon/index.js 
lando 12:02:27 DEBUG ==> plugin lando-platformsh loaded from /snapshot/lando/build/cli/integrations/lando-platformsh/index.js 
lando 12:02:27 DEBUG ==> emitting event post-bootstrap-config 
lando 12:02:27 VERBOSE ==> building proxy config... 
lando 12:02:27 VERBOSE ==> config bootstrap completed. 
lando 12:02:27 VERBOSE ==> tasks bootstrap beginning... 
lando 12:02:27 DEBUG ==> emitting event pre-bootstrap-tasks 
lando 12:02:27 DEBUG ==> autoloaded task config 
lando 12:02:27 DEBUG ==> autoloaded task destroy 
lando 12:02:27 DEBUG ==> autoloaded task info 
lando 12:02:27 DEBUG ==> autoloaded task list 
lando 12:02:27 DEBUG ==> autoloaded task logs 
lando 12:02:27 DEBUG ==> autoloaded task poweroff 
lando 12:02:27 DEBUG ==> autoloaded task rebuild 
lando 12:02:27 DEBUG ==> autoloaded task restart 
lando 12:02:27 DEBUG ==> autoloaded task share 
lando 12:02:27 DEBUG ==> autoloaded task start 
lando 12:02:27 DEBUG ==> autoloaded task stop 
lando 12:02:27 DEBUG ==> autoloaded task version 
lando 12:02:27 DEBUG ==> autoloaded task init 
lando 12:02:27 DEBUG ==> autoloaded task ssh 
lando 12:02:27 DEBUG ==> emitting event post-bootstrap-tasks 
lando 12:02:27 VERBOSE ==> tasks bootstrap completed. 
lando 12:02:27 VERBOSE ==> engine bootstrap beginning... 
lando 12:02:27 DEBUG ==> emitting event pre-bootstrap-engine 
lando 12:02:27 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-core/scripts to /home/brad/.lando/scripts and set to mode 755 
lando 12:02:27 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-proxy/scripts to /home/brad/.lando/scripts and set to mode 755 
lando 12:02:27 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-recipes/scripts to /home/brad/.lando/scripts and set to mode 755 
lando 12:02:27 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-services/scripts to /home/brad/.lando/scripts and set to mode 755 
lando 12:02:27 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-sharing/scripts to /home/brad/.lando/scripts and set to mode 755 
lando 12:02:27 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/integrations/lando-acquia/scripts to /home/brad/.lando/scripts and set to mode 755 
lando 12:02:27 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/integrations/lando-lagoon/scripts to /home/brad/.lando/scripts and set to mode 755 
lando 12:02:27 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/integrations/lando-pantheon/scripts to /home/brad/.lando/scripts and set to mode 755 
lando 12:02:27 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/integrations/lando-platformsh/scripts to /home/brad/.lando/scripts and set to mode 755 
lando 12:02:27 DEBUG ==> emitting event post-bootstrap-engine 
lando 12:02:27 VERBOSE ==> engine bootstrap completed. 
lando 12:02:27 VERBOSE ==> bootstrap completed. 
lando 12:02:27 DEBUG ==> emitting event post-bootstrap 
lando 12:02:27 VERBOSE ==> docker-engine exists: true 
lando 12:02:27 VERBOSE ==> docker-compose exists: true 
lando 12:02:27 DEBUG ==> emitting event cli-answers 
lando 12:02:27 DEBUG ==> emitting event cli-platform-answers 
lando 12:02:27 DEBUG ==> emitting event cli-run 
lando 12:02:27 DEBUG ==> emitting event cli-platform-run 
lando 12:02:27 DEBUG ==> emitting event pre-command-runner 
lando 12:02:27 DEBUG ==> emitting event pre-platform 
lando 12:02:27 DEBUG ==> process pid4 running /usr/bin/docker exec avenueroad_app_1 /helpers/psh-exec.sh platform env cstdio=[inherit, pipe, pipe], silent=false, mode=attach, detached=false
lando 12:02:28 DEBUG ==> engine is up. 
                                       lando 12:02:28 DEBUG ==> docker is running. 
                                                                                   Project ID read from environment variable PLATFORM_PROJECT: e3ffbb26c1779cece8e60dfc481882c368fb50dd
lando 12:02:29 VERBOSE ==> checking docker version compatibility... 
                                                                    lando 12:02:29 DEBUG ==> compatibility results name=compose, link=https://docs.docker.com/compose/install/#install-compose-on-linux-systems, wants=1.23.0 - 1.29.0, version=1.29.1, semversion=1.29.1, semmin=1.23.0, semmax=1.29.0, dockerVersion=true, satisfied=false, name=engine, link=https://docs.docker.com/engine/install/, wants=18.09.3 - 20.10.99, version=20.10.6, semversion=20.10.6, semmin=18.9.3, semmax=20.10.99, dockerVersion=true, satisfied=true

                                                                         
  [InvalidArgumentException]                                             
  Specified project not found: e3ffbb26c1779cece8e60dfc481882c368fb50dd  
                                                                         
  Your projects are:                                                     
      ftqlitxucutyq - Avenue Road                                        
                                                                         
```
*lando push:*

```bash

lando       12:05:15 DEBUG ==> emitting event cli-run 
lando       12:05:15 DEBUG ==> emitting event cli-push-run 
lando       12:05:15 INFO ==> loading app avenue-road from config files 0=/home/brad/projects/avenue-road/.lando.upstream.yml, 1=/home/brad/projects/avenue-road/.lando.yml
lando       12:05:15 DEBUG ==> app avenue-road has config name=avenue-road, recipe=platformsh, system.file:path:temporary=/tmp, skip_permissions_hardening=1, service=app, service=node, service=node, service=node, type=node:12, gulp-cli=latest
lando       12:05:15 DEBUG ==> emitting event pre-app-runner 
lando       12:05:15 DEBUG ==> emitting event pre-command-runner 
avenue-road 12:05:15 VERBOSE ==> initiatilizing app at /home/brad/projects/avenue-road... 
lando       12:05:15 DEBUG ==> plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/app.js 
lando       12:05:15 DEBUG ==> plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/app.js 
lando       12:05:15 DEBUG ==> plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/app.js 
avenue-road 12:05:15 VERBOSE ==> proxy settings detected. 
lando       12:05:15 DEBUG ==> plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/app.js 
lando       12:05:15 DEBUG ==> plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/app.js 
lando       12:05:15 DEBUG ==> plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/app.js 
lando       12:05:15 DEBUG ==> plugin lando-sharing loaded from /snapshot/lando/build/cli/plugins/lando-sharing/app.js 
lando       12:05:15 DEBUG ==> plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/app.js 
lando       12:05:15 DEBUG ==> plugin lando-acquia loaded from /snapshot/lando/build/cli/integrations/lando-acquia/app.js 
lando       12:05:15 DEBUG ==> plugin lando-lagoon loaded from /snapshot/lando/build/cli/integrations/lando-lagoon/app.js 
lando       12:05:15 DEBUG ==> plugin lando-pantheon loaded from /snapshot/lando/build/cli/integrations/lando-pantheon/app.js 
avenue-road 12:05:15 VERBOSE ==> identified a platformsh app 
avenue-road 12:05:15 DEBUG ==> reset app id to e3ffbb26c1779cece8e60dfc481882c368fb50dd 
avenue-road 12:05:15 DEBUG ==> ensured /home/brad/.lando/config/avenue-road exists 
avenue-road 12:05:15 DEBUG ==> local override on app with {"variables":{"d8config":{"system.file:path:temporary":"/tmp"},"d8settings":{"skip_permissions_hardening":1}}} 
lando       12:05:15 DEBUG ==> plugin lando-platformsh loaded from /snapshot/lando/build/cli/integrations/lando-platformsh/app.js 
avenue-road 12:05:15 DEBUG ==> emitting event pre-init 
avenue-road 12:05:15 VERBOSE ==> parsed platformsh routes 
avenue-road 12:05:15 VERBOSE ==> parsed platformsh applications 
avenue-road 12:05:15 VERBOSE ==> the closest platform app is at undefined 
avenue-road 12:05:15 VERBOSE ==> the closest open cache is { database: [Array], redis: [Array] } 
avenue-road 12:05:15 VERBOSE ==> determined platformsh relationships 
avenue-road 12:05:15 VERBOSE ==> parsed platformsh services 
avenue-road 12:05:15 VERBOSE ==> built platformsh config jsons 
avenue-road 12:05:15 VERBOSE ==> building platformsh recipe named 
lando       12:05:15 VERBOSE ==> proxy is ON. 
lando       12:05:15 VERBOSE ==> Setting the default proxy certificate /certs/cert.crt 
avenue-road 12:05:15 VERBOSE ==> building platformsh-php service app 
avenue-road 12:05:15 VERBOSE ==> building platformsh-mariadb service db 
avenue-road 12:05:15 VERBOSE ==> building platformsh-redis service cache 
avenue-road 12:05:15 VERBOSE ==> building node service node 
avenue-road 12:05:15 DEBUG ==> emitting event post-init 
avenue-road 12:05:15 DEBUG ==> adding hostnames to the app... 
avenue-road 12:05:15 DEBUG ==> hostnames added to app 0=app.avenueroad.internal
avenue-road 12:05:15 DEBUG ==> hostnames added to db 0=db.avenueroad.internal
avenue-road 12:05:15 DEBUG ==> hostnames added to cache 0=cache.avenueroad.internal
avenue-road 12:05:15 DEBUG ==> hostnames added to node 0=node.avenueroad.internal
avenue-road 12:05:15 VERBOSE ==> attempting to find open services... 
avenue-road 12:05:15 DEBUG ==> engine is up. 
avenue-road 12:05:15 VERBOSE ==> refreshing certificates... 0=app, 1=db, 2=cache, 3=node
avenue-road 12:05:15 VERBOSE ==> analyzing user ssh keys... using 3 of 3 
avenue-road 12:05:15 DEBUG ==> key config...  none 
avenue-road 12:05:15 VERBOSE ==> additional tooling detected 
avenue-road 12:05:15 DEBUG ==> adding app cli task platform 
avenue-road 12:05:15 DEBUG ==> adding app cli task composer 
avenue-road 12:05:15 DEBUG ==> adding app cli task php 
avenue-road 12:05:15 DEBUG ==> adding app cli task database 
avenue-road 12:05:15 DEBUG ==> adding app cli task redis 
avenue-road 12:05:15 DEBUG ==> adding app cli task pull 
avenue-road 12:05:15 DEBUG ==> adding app cli task push 
avenue-road 12:05:15 DEBUG ==> adding app cli task drush 
avenue-road 12:05:15 DEBUG ==> adding app cli task node 
avenue-road 12:05:15 DEBUG ==> adding app cli task npm 
avenue-road 12:05:15 DEBUG ==> adding app cli task gulp 
avenue-road 12:05:15 VERBOSE ==> preparing to OPEN up platformsh containers... 
avenue-road 12:05:15 DEBUG ==> found platformsh services to open 0=db, 1=cache
avenue-road 12:05:15 DEBUG ==> found platformsh appservers to open 0=app
avenue-road 12:05:15 VERBOSE ==> setting LANDO_INFO... 
avenue-road 12:05:15 DEBUG ==> ensuring exposed ports on app are bound to 127.0.0.1 
avenue-road 12:05:15 DEBUG ==> ensuring exposed ports on db are bound to 127.0.0.1 
avenue-road 12:05:15 DEBUG ==> ensuring exposed ports on db are bound to 127.0.0.1 
avenue-road 12:05:15 DEBUG ==> ensuring exposed ports on cache are bound to 127.0.0.1 
avenue-road 12:05:15 DEBUG ==> ensuring exposed ports on cache are bound to 127.0.0.1 
avenue-road 12:05:15 VERBOSE ==> app is ready! 
avenue-road 12:05:15 DEBUG ==> emitting event ready 
avenue-road 12:05:15 VERBOSE ==> discovering dynamic portforward info... 
avenue-road 12:05:16 DEBUG ==> emitting event pre-push 
avenue-road 12:05:16 DEBUG ==> process pid6 running /usr/bin/docker exec avenueroad_app_1 /helpers/psh-push.sh cstdio=[inherit, pipe, pipe], silent=false, mode=attach, detached=false
Verifying you are authenticated against platform.sh...
+--------------+--------------------------------------+
| Property     | Value                                |
+--------------+--------------------------------------+
| id           | c40aa7eb-a568-41d0-a663-345a0bb6e788 |
| display_name | Bradley Baylis                       |
| username     | bradley-baylis                       |
| mail         | Bradley.Baylis@walthamforest.gov.uk  |
| has_key      | true                                 |
+--------------+--------------------------------------+
Verifying your current project...

                                                                         
  [InvalidArgumentException]                                             
  Specified project not found: e3ffbb26c1779cece8e60dfc481882c368fb50dd  
                                                                         
  Your projects are:                                                     
      ftqlitxucutyq - Avenue Road                                        
                                                                         

Usage: platform project:info [--refresh] [--date-fmt DATE-FMT] [--format FORMAT] [--columns COLUMNS] [--no-header] [-p|--project PROJECT] [--host HOST] [-W|--no-wait] [--wait] [--] [<property>] [<value>]

For more information, type: platform help project:info

Verified project id: 
Verifying feature/text-img-paragraphs is an active environment...

                                                                         
  [InvalidArgumentException]                                             
  Specified project not found: e3ffbb26c1779cece8e60dfc481882c368fb50dd  
                                                                         
  Your projects are:                                                     
      ftqlitxucutyq - Avenue Road                                        
                                                                         

Usage: platform environment:list [-I|--no-inactive] [--pipe] [--refresh REFRESH] [--sort SORT] [--reverse] [--format FORMAT] [--columns COLUMNS] [--no-header] [-p|--project PROJECT] [--host HOST]

For more information, type: platform help environment:list

Branch feature/text-img-paragraphs is inactive... using the parent environment (master) instead
Verified the master environment is active
Verifying your ssh keys work are deployed to the project...
Could not connect over SSH correctly...
platformsh 11:05:22.01 INFO  ==> Redeploying environment to reload keys...

                                                                         
  [InvalidArgumentException]                                             
  Specified project not found: e3ffbb26c1779cece8e60dfc481882c368fb50dd  
                                                                         
  Your projects are:                                                     
      ftqlitxucutyq - Avenue Road                                        
                                                                         

Usage: platform redeploy [-p|--project PROJECT] [--host HOST] [-e|--environment ENVIRONMENT] [-W|--no-wait] [--wait]

For more information, type: platform help environment:redeploy

avenue-road 12:05:23 DEBUG ==> process pid6 finished with exit code 1 
avenue-road 12:05:23 DEBUG ==> engine is up. 
                                                                         
```
**Tell us generally about your bug**

I'm trying to push all my drupal files to my Platform env, but I keep coming up against 

```bash

[InvalidArgumentException]                                             
  Specified project not found: e3ffbb26c1779cece8e60dfc481882c368fb50dd  

```
I noticed this same error for lando platform env, when I was trying to debug it.  I've found that $PLATFORM_PROJECT=e3ffbb26c1779cece8e60dfc481882c368fb50dd and $PLATFORM_TREE_ID=e3ffbb26c1779cece8e60dfc481882c368fb50dd-app, which seems to be the issue as per the logs below.  I'm not sure where this id is coming from because it isn't anywhere in my project files and the correct id is ftqlitxucutyq.  Also noteworthy is that platform env works as expected on my cmd line outside of the lando instance.

```bash
lando 12:02:28 DEBUG ==> docker is running.  Project ID read from environment variable PLATFORM_PROJECT: e3ffbb26c1779cece8e60dfc481882c368fb50dd // lanod platform env -vvv
avenue-road 12:05:15 DEBUG ==> reset app id to e3ffbb26c1779cece8e60dfc481882c368fb50dd // lando push -vvv
```
Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
1. lando start
2. lando auth:api-token-login
3a. lando platform env
3b. lando push (relationships: database, mounts: /web/sites/default/files, /tmp, /private, /.drush, /drush-backups, /.console)
```
