### ISSUE TITLE
platform.sh recipe: source in multi command tooling not working

### ISSUE THREAD

**Issue by simonkey** [lando/platformsh#36]
When using the platform.sh recipe the tooling does not work as expected as described in https://docs.lando.dev/config/tooling.html#multi-command-tooling. 

I've created a simple tooling command

```yaml
tooling:
    test:
        cmd:
            - source .bashrc
            - echo "hello"
    test2:
        cmd:
            - echo "hello"
```

Calling `lando test` results in the error: 
`/helpers/psh-exec.sh: 36: exec: source: not found`

If I call `lando test2` "hello" is echoed.

Lando version: 3.0.28
