### ISSUE TITLE
platform.sh recipe: CLI xdebug not working

### ISSUE THREAD

**Issue by simonkey** [lando/platformsh#38]
There seems to be a problem with the platform.sh recipe and xdebug for CLI commands, e.g. via lando php bin/console some:cli:command.

Lando version: v3.0.26

`.platform.app.yaml`:
```yml
name: api
type: php:7.4
build:
    flavor: composer
runtime:
    xdebug:
        idekey: PHPSTORM
    extensions:
...
        - xdebug # tried with and without extension
        - ...
```
`.lando.yml`:
```yml
name: mayspeedguide
recipe: platformsh
config:
  id: xxx
  via: nginx
  xdebug: true
```
I've followed the instructions in https://docs.lando.dev/guides/lando-phpstorm.html#debugging-drush-commands, but its *only* working for requests from the browser and not via CLI command.

As solution I've tried to set the enviroment variable `XDEBUG_CONFIG` manually, with `remote_enable=1 remote_mode=req remote_port=9000 remote_host=xxx remote_connect_back=0`. Unfortunately this seems not to work, especially the dynamic ip for `remote_host` cannot be set easily. Furthermore change this settings depending on the xdebug version (2 or 3).

I've tried the symfony recipe and here the debugging worked nearly out of the box for CLI commands.
