### ISSUE TITLE
Platform Recipe + Xdebug Winning & some PHPStorm wins

### ISSUE THREAD

**Issue by labboy0276** [lando/platformsh#51]
@pirog @mikemilano as you know form our talks internally, this is how I got XDebug to work correctly with the platform.sh recipe.  Added bonus, how I got it to work in PHPStorm.

## Configuring XDebug:

1. Add this to your extensions in your .platform.app.yml

```yaml
runtime:
    extensions:
        - xdebug
```

2.  Add this to your .lando.yml

```yaml
config:
  id: whateveryouridis
  variables:
    app:
      php:
        xdebug.remote_connect_back: 1
```

3. Profit.

## PHPStorm Setup

1. We need to manually setup the CLI Interpreter.  The main take aways are:
 a. Use the docker.registry.platform.sh/php-whateverversion image
 b. You will need to manually add the xdebug.so the the debugger extension in the CLI Interpreter screen.  I show how to do this [at this point in the migration webinar](https://youtu.be/C1lhgObpHd8?t=2430).  You need to run this to find it:
  
```bash
lando ssh -s app -u root
find / -name '*xdebug.so'
```

2. Then you can just setup your debug point and it will pick up the server once you refresh your page.

3. Added bonus, exclude the _www folder from PHPStorm's index as it will constantly try to index it slowing the IDE down.  You can do this by going to File -> Settings -> Directories.
