### ISSUE TITLE
platform recipe should configure mailhog out of the box

### ISSUE THREAD

**Issue by lsmith77** [lando/platformsh#56]
It would be sensible to configure mailhog out of the box.

I guess something like:
```
name: app

proxy:
  mailhog:
    - mail.lndo.site

services:
  mailhog:
    type: mailhog
    portforward: 1025
    hogfrom:
      - app
```

Note there is another issue, it seems like the platform.sh image has a `MAIL_HOST` env variable set to `localhost` which in the above case would need to be `mailhog` instead.
