### ISSUE TITLE
Platform.sh recipe, MariaDB 10.5 unavailable when connecting

### ISSUE THREAD

**Issue by gilzow** [lando/platformsh#63]
**Tl;DR** - changing database service from `mariadb:10.4` to `mariadb:10.5` causes the database service to be unaccessible: `ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)`. Changing the db service back to 10.4 and rebuilding allows the db service to be available again.

**Lando version**: 3.3.2
**OS version**: macOS 11.6

Contents of .lando.yml
```yaml
name: mariadb-10.5-test
recipe: platformsh
```

Using the default [Platform.sh WordPress composer template.](https://github.com/platformsh-templates/wordpress-composer) 

**Contents of** `/.platform/services.yml`:
```yaml
db:
    type: mariadb:10.5
    disk: 2048
```
**Contents of** `.platform.app.yml`
```yaml
# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:7.4"

# Configuration of the build of the application.
build:
    flavor: composer

dependencies:
    php:
        composer/composer: '^2'
        wp-cli/wp-cli: "^2.2.0"

hooks:
    build: |
        set -e
        # Copy manually-provided plugins into the plugins directory.
        # This allows manually-provided and composer-provided plugins to coexist.
        rsync -a plugins/* wordpress/wp-content/plugins/

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "db:mysql"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "wordpress"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"
            # Wordpress has multiple roots (wp-admin) so the following is required
            index:
                - "index.php"
            # The number of seconds whitelisted (static) content should be cached.
            expires: 600
            scripts: true
            allow: true
            rules:
                ^/composer\.json:
                    allow: false
                ^/license\.txt$:
                    allow: false
                ^/readme\.html$:
                    allow: false
        "/wp-content/cache":
            root: "wordpress/wp-content/cache"
            scripts: false
            allow: false
        "/wp-content/uploads":
            root: "wordpress/wp-content/uploads"
            scripts: false
            allow: true

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "wordpress/wp-content/cache":
        source: local
        source_path: "cache"
    "wordpress/wp-content/uploads":
        source: local
        source_path: "uploads"

```
**Tell us about the command you were running**

After bringing up lando (`lando start`) and attempting to access the database (`lando database`), causes the error `ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)`. Changing the version back to 10.4 and rebuilding (via `lando rebuild`) allows the db service to be available again. 

Info from `lando info`:
```
{ service: 'db',
    urls: [],
    type: 'platformsh-mariadb',
    healthy: true,
    creds:
     [ { internal_hostname: 'database.internal', path: 'main', port: 3306, user: 'user' } ],
    internal_connection: { host: 'db', port: '3306' },
    external_connection: { host: '127.0.0.1', port: '51365' },
    config: {},
    version: '10.5',
    meUser: 'app',
    hasCerts: false,
    hostnames: [ 'db.mariadb105test.internal' ] } 
```

Similar if not identical issue to lando/platformsh#61
