### ISSUE TITLE
Expose `psysh` for lando-platformsh php recipes.

### ISSUE THREAD

**Issue by serundeputy** [lando/platformsh#70]
The `lando-platformsh` (at least for php apps) has `psysh` in the app container.  This tooling works to expose it to the user:

```yaml
tooling:
  psysh:
    service: app
```
Can we expose that to the user by default for PHP apps?
