### ISSUE TITLE
p.sh Elasticsearch fails to start correctly.

### ISSUE THREAD

**Issue by pirog** [lando/platformsh#97]
Fairly easy to replicate this:

1. `lando init` the `lando-d8` site, or `lando destroy` the site if already have it
2. Add a trivial ES instance to `services.yaml`

```yaml
db:
    type: mariadb:10.2
    disk: 2048

cache:
    type: redis:5.0

searchelastic:
    type: elasticsearch:7.2
    disk: 256
```
3. `lando start`, this should error (you may need to `lando restart`)
4. `docker logs landod8_searchelastic_1`
